import React from "react";
const About = ()=> {
    return(
        <div className="container clr my-5 rounded-5">
            <div className="py-4">
                <h1>About Pages</h1>
               <div>
                 <p className="adi mb-4 mt-3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint, laudantium. Fuga nobis dignissimos reiciendis cumque ipsum quibusdam error, laboriosam incidunt doloremque impedit! Recusandae fuga esse dolore dolores voluptas nam eaque ad quis necessitatibus dolor?Lorem ipsum dolor sit amet consectetur adipisicing elit. Id minus rem quasi? Deserunt doloremque quis vel, hic eum quibusdam ipsum aliquid sequi praesentium veniam asperiores ut, voluptate aperiam sint soluta obcaecati aspernatur commodi! Nulla modi dolorem minima id dolore! Rerum veniam odit earum doloremque mollitia ratione odio dolor saepe. Ullam quam architecto natus fugit id rerum quibusdam libero quia est iste. Iure assumenda possimus illo nam deserunt? Similique, aspernatur cum. Fugiat dignissimos aspernatur animi eos doloremque voluptatum dolores? Fuga quos beatae delectus hic culpa incidunt repellat itaque facilis. Tenetur quae accusamus est nihil eaque quasi quo quisquam cum eos Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, expedita molestias impedit possimus eius repellendus at. Modi nostrum culpa aut tempore pariatur magni autem architecto fugit minus ut. Eos, sapiente. Deserunt expedita molestiae nihil sed voluptatibus perferendis quae provident. Illo optio mollitia odit, deleniti ratione repellat sit commodi culpa odio maxime voluptatibus soluta accusamus, numquam assumenda! Tempore quibusdam, praesentium dicta voluptatum temporibus ipsam enim magni quasi soluta autem eveniet?</p>
                <p className="adi mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim iure atque accusantium corrupti corporis! Facere perferendis vel culpa. Numquam tempora, reiciendis vel, nam et quibusdam veritatis optio repudiandae temporibus illo porro sint officia! Eos libero exercitationem iste accusantium rem, magnam distinctio suscipit repellendus numquam. Id iste et numquam esse delectus corrupti. Fugiat quis illo quo adipisci. Animi provident enim at, assumenda ratione dolore sunt voluptatibus quisquam molestiae dolorum pariatur, officia delectus vero, asperiores temporibus accusantium ad iusto sed dicta. Eum consequuntur quasi incidunt, dolorem molestiae fugiat alias perspiciatis saepe ratione facere eius nam fugit nisi, aspernatur earum recusandae, molestias adipisci soluta magnam amet error accusamus nostrum autem. Sed quod natus ratione dolorum ab, ullam dolor earum! Voluptates ipsa nobis ratione esse similique deleniti ipsum harum sapiente rerum est, laborum incidunt dolorem culpa sed recusandae rem odit, aliquid quae quod debitis. Ducimus iusto reiciendis aliquam nobis cumque quam error adipisci vel voluptatem nihil beatae aspernatur, eius distinctio rerum impedit molestiae! Odit expedita ad minima quos doloribus rem vero necessitatibus accusamus voluptatem corrupti. Architecto ducimus, maiores consectetur magnam facilis, accusamus quas minima dolorem voluptatem animi omnis vel iste porro asperiores ab nulla provident! Nulla, provident ex! Sint, esse libero? Earum, placeat tempore.</p>
                <p className="adi mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi delectus libero excepturi ex beatae similique, quae sapiente provident, iste nihil cumque velit laborum optio soluta vel magnam nisi facere accusantium pariatur ducimus labore minima fugit! Veritatis praesentium ea ratione maxime! Voluptates obcaecati neque omnis necessitatibus dolore delectus saepe, nobis sint magni quae cum nostrum mollitia hic quia laudantium doloribus sapiente ea, temporibus repellat. Quisquam repellendus ex aliquid harum sit officia voluptate voluptatem nihil facilis molestias distinctio id, quis, libero, natus magni asperiores at porro mollitia ut fugit autem quo. Ratione, nemo, tenetur tempore voluptatem provident perferendis rerum quos quas ad illo facere quia cumque vero dolorem iusto et ex cum fugiat at. Molestias doloribus quas eveniet repudiandae obcaecati qui, quisquam id voluptatem temporibus natus earum laudantium perspiciatis tempore hic autem dolores facere aspernatur eius error sapiente necessitatibus exercitationem quos fugit. Voluptatem, adipisci perferendis nisi labore id quas voluptatibus distinctio alias temporibus excepturi. Impedit quibusdam dolorum inventore asperiores veritatis quod omnis eligendi suscipit itaque dolor placeat consequatur dolorem deleniti consequuntur earum, in sit aliquam excepturi mollitia cum perspiciatis ullam distinctio ex at! A, velit. Et suscipit tenetur esse architecto repudiandae dolore animi laudantium libero rem sint, obcaecati sunt eum eaque repellat ratione blanditiis, deserunt voluptates! Quo, officiis quaerat. Ad dolores, dicta alias aliquid architecto porro atque adipisci nobis, in quasi quibusdam necessitatibus accusantium reiciendis itaque, distinctio sunt delectus fugiat amet magni vero quod ipsa nam. In dicta libero, voluptatum rem quam repellendus ipsum dolor itaque tempora fugiat quos inventore explicabo </p>
               </div>
            </div>
        </div>
    );
};

export default About;